---
title: promise 개념부터 활용까지
categories: [JavaScript]
tags:  [promise]
---

promise는 무엇인지, 콜백을 대체해서 어떻게 깔끔하게 작성할 수 있는지 알아보자

## Promise

promise는 자바스크립트에서 제공하는 오브젝트로 비동기를 간편하게 처리할 수 있게 해준다.



#### state

state는 비동기 처리의 진행 상태를 나타내며 세 가지 상태가 있다.

* pending: 비동기 처리가 아직 완료되지 않은 상태
* fulfilled: 비동기 처리가 성공적으로 완료되어 결과 값을 반환해준 상태
* rejected: 비동기 처리에 실패하거나 처리 중 에러가 발생한 상태



#### producer

`new <T>(executor: (resolve: (value?: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void): Promise<T>;`

producer는 비동기 처리 시 원하는 기능을 수행하고 완료됐을 때 resolve와 reject 콜백 함수를 실행한다.

producer가 생성된 순간 excutor가 자동으로 실행된다.



**resolve: ** 값 또는 다른 promise의 결과로 promise를 해결하는 데 사용되는 콜백

**reject:**  제공된 이유 또는 오류와 함께 promise를 거부하는 데 사용되는 콜백



```javascript
const promise = new Promise((resolve, reject) =>  {
  // doing some heavy work like  network, read files ...
  console.log('doing something...');
  setTimeout(() => {
    resolve('yghee');
    // reject(new Error('no network'));
  }, 2000);
});
```



#### consumer

consumer은 promise가 resolve나 reject됐을 때 then, catch, finally로 처리한다.



**then**

`then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): Promise<TResult1 | TResult2>;`

promise에서 반환한 resolve나 reject의 결과를 처리하기 위한 콜백을 첨부한다.

**onfulfilled:**  promise가 resolve됐을 때 실행하는 콜백

**onrejected:**  promise가 reject됐을 때 실행하는 콜백



**catch**

`catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): Promise<T | TResult>;`

promise가 reject됐을 때만 사용하는 콜백



**finally**

새로 추가된 처리 방법으로 promise의 성공 실패 여부와 상관없이 사용하는 콜백



```javascript
promise
  .then((value) => {
  console.log(value);
  })
  .catch(error => {
    console.log(error);
  })
  .finally(() => {
    console.log('finally');
  });
```



#### promise chaining

promise는 여러 개의 promise를 연결하여 사용할 수 있다.

``` javascript
const fetchNumber = new Promise((resolve, reject) => {
  setTimeout(() => resolve(1), 1000);
});

fetchNumber
  .then(num => num * 2) // 2
  .then(num => num * 3) // 6
  .then(num => {
    return new Promise((resolve, reject) => {
      setTimeout(() => resolve(num - 1), 1000);
    }); 
  })
  .then(num => console.log(num)); // 5
```



#### error handling

promise chaining을 할 때 중간에 reject가 발생할 수 있다.

reject가 발생 시 catch를 통해 에러에 대한 대응을 하자.

```javascript
const getHen = () =>
  new Promise((resolve, reject) => {
    setTimeout(() => resolve('🐓'), 1000);
  });
const getEgg = hen =>
  new Promise((resolve, reject) => {
    setTimeout(() => reject(new Error(`${hen} => 🥚`)), 1000);
  });
const cook = egg =>
  new Promise((resolve, reject) => {
    setTimeout(() => resolve(`${egg} => 🍳`), 1000);
});

getHen()
  .then(getEgg)
  .catch(error => {
    return '🥖';
  })
  .then(cook)
  .then(console.log)
  .catch(console.log);
```



#### callback to promise

**callback으로만 구현한 코드**

```javascript
class UserStorage {
  loginUser(id, password, onSuccess, onError) {
    setTimeout(() => {
      if(
        (id === 'yghee' && password === 'dream') ||
        (id === 'coder' && password === 'academy')
      ) {
        onSuccess(id);
      } else {
        onError(new Error('not found'));
      }
    }, 2000);

  }

  getRoles(user, onSuccess, onError) {
    setTimeout(() => {
      if(user === 'yghee') {
        onSuccess({name: 'yghee', role: 'admin'});
      }else {
        onError(new Error('no access'));
      }
    }, 1000);
  }
}

const userStorage = new UserStorage();
const id = prompt('enter your id');
const password = prompt('enter your password');
userStorage.loginUser(
  id, 
  password, 
  (user) => {
    userStorage.getRoles(
      user, 
      (userWithRole) => {
        alert(`Hello ${userWithRole.name}, you have a ${userWithRole.role} role`);
      },
      (error) => {
        console.log(error);
      }
    );
  }, 
  (error) => {
    console.log(error);
  })
```

**promise로 refactoring한 코드**

```javascript
class UserStorage {
  loginUser(id, password) {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        if(
          (id === 'yghee' && password === 'dream') ||
          (id === 'coder' && password === 'academy')
        ) {
          resolve(id);
        } else {
          reject(new Error('not found'));
        }
      }, 2000);
    });
  }

  getRoles(user) {
    return new Promise((resolve, reject) => {
    setTimeout(() => {
      if(user === 'yghee') {
        resolve({name: 'yghee', role: 'admin'});
      }else {
        reject(new Error('no access'));
      }
    }, 1000);
    });
  }
}

const userStorage = new UserStorage();
const id = prompt('enter your id');
const password = prompt('enter your password');

userStorage.loginUser(id, password)
  .then(userStorage.getRoles)
  .then(user => 
    alert(
      `Hello ${user.name}, you have a ${user.role} role`
      ))
  .catch(console.log);
```



**callback을 parameter로 받지 않아도 되며  consumer 부분의 가독성이 매우 높아진 것을 볼 수 있다.**